=== gre99ory/flesh-and-blood-cards/json-schema/legality-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "An array of all of the current card legality changes for a particular Flesh and Blood format and legality type (banned, suspended, or living legend).",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "unique_id": {
                "description": "The unique identifier for this legality change entry within the data set.",
                "type": "string"
            },
            "card_unique_id": {
                "description": "The unique identifier for the card the legality change is for.",
                "type": "string"
            },
            "status_active": {
                "description": "If this legality change was becoming active or inactive (True means this card is now banned/suspended/living legend, False means this card stopped being banned/suspended/living legend).",
                "type": "boolean"
            },
            "date_announced": {
                "description": "The date this legality change was announced on, but did not necessarily become active on.",
                "type": "string"
            },
            "date_in_effect": {
                "description": "The date this legality change went into effect on.",
                "type": "string"
            },
            "planned_end": {
                "description": "The date this legality change was planned to revert on.",
                "type": "string"
            },
            "legality_article": {
                "description": "The URL to the article detailing this change.",
                "type": "string"
            }
        },
        "required": [
            "unique_id",
            "card_unique_id",
            "status_active",
            "date_announced",
            "date_in_effect",
            "legality_article"
        ]
    }
}

=== gre99ory/flesh-and-blood-cards/json/english/banned-upf.json
[
    {
        "unique_id": "kpzpQpHnMDNwNT7wmkMBD",
        "card_unique_id": "nrMg9kDMg9KwBPPtJLJph",
        "status_active": true,
        "date_announced": "2022-10-03T00:00:00.000Z",
        "date_in_effect": "2022-10-07T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-suspended-oct-3/"
    }
]

=== gre99ory/flesh-and-blood-cards/json/english/living-legend-cc.json
[
    {
        "unique_id": "LDnrPtTN9dzCQrhwnKt8z",
        "card_unique_id": "PFJnMWQNfr6jMMzJhjB9H",
        "status_active": true,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "GjJLF8cJkwpwdf68kgQFp",
        "card_unique_id": "MhBTRHCCft7RbrMmkwwGw",
        "status_active": true,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "JchW8rpMgHwfkwdpkKqbn",
        "card_unique_id": "r8Bq8zBCNdzGPkmMcr6QL",
        "status_active": true,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "DgWD9pDz7mNkhgmPznkrg",
        "card_unique_id": "F7rQpTDjHFWPgQhcGg7RT",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "wtjFb6JncgRT8nHh8jG7q",
        "card_unique_id": "TQ7Twhtm6zfkTTHTKdpJK",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    }
]

=== gre99ory/flesh-and-blood-cards/json/english/restricted-ll.json
[
    {
        "unique_id": "mzJKMmjwtkBzThtDFrmFQ",
        "card_unique_id": "phCFwdjG8dKDCmr7d7F7M",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "bW8c9MNDCJcWF7RphDbqk",
        "card_unique_id": "frQkkTNgtwqhkN6Hgq6cj",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "Nk7rTCmjdC7fkmMkPPCQD",
        "card_unique_id": "j8jjnw6NmpTpf9cWThfgg",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "87qq9j9nRTHDW7Nqcmkfm",
        "card_unique_id": "HFwjczQFRKCgTFHdbjdzW",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "998HqzjRCJpGTNGNHFPH7",
        "card_unique_id": "JfJ7hNnCDL9GDCwfrWBBc",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "79kDq7wL6gJfwt8jQJtwQ",
        "card_unique_id": "zzHRCMBmNTF9KpJMqKWq8",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    },
    {
        "unique_id": "kwPrDHpK86qTgKfGgKhqR",
        "card_unique_id": "BkpMHRn6L8dpcgjgrPm9H",
        "status_active": true,
        "date_announced": "2023-12-18T00:00:00.000Z",
        "date_in_effect": "2023-12-22T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-restricted-announcement-eoy/"
    }
]

=== gre99ory/flesh-and-blood-cards/json/english/living-legend-blitz.json
[
    {
        "unique_id": "MQTLKPtWrbNpRrjjPhzn8",
        "card_unique_id": "RHnFkKb8FKdFzp9rdzGjF",
        "status_active": true,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "fPzpnpKpJDp86fzN6GpMr",
        "card_unique_id": "RWwk8hgBdnRdWfjkrfJHt",
        "status_active": true,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    }
]

=== gre99ory/flesh-and-blood-cards/json/english/suspended-cc.json
[
    {
        "unique_id": "JGCjqRTFRgTCmw8MfwLnL",
        "card_unique_id": "nwNfL8wPDtKW9jCFktCBL",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": "until Bravo, Star of the Show becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "KCKd9HgMBj6gjWrDTjdmp",
        "card_unique_id": "pKdGGghdpnBCzrjwPmkPg",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": "until Bravo, Star of the Show becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "77GQLzbFmNP67r66c7gCh",
        "card_unique_id": "QqghkNGDQHkGMRGRt8pDr",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": "until Bravo, Star of the Show becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "pnkhGKRBrpFCKmjtnBn9C",
        "card_unique_id": "nGHhHDgKmGgb7gjwWjHJF",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": "until Viserai, Rune Blood becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "hggkqJHhzFcpTGnpGjbfp",
        "card_unique_id": "bkwMDWGMmKTMd9dKQMt76",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": " until Chane, Bound by Shadow becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "7DHkr86cjKQnfbJRgkBHp",
        "card_unique_id": "g9ckPjGmpNNkmbgChTQNR",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": " until Chane, Bound by Shadow becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "PDJmGJNhD6hQkmTg8pHbt",
        "card_unique_id": "BnQtggKJtBNmpqKR7NWBH",
        "status_active": true,
        "date_announced": "2022-04-22T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "planned_end": " until Chane, Bound by Shadow becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "zHtrfgJtMzrRH8jCNTpJR",
        "card_unique_id": "nwNfL8wPDtKW9jCFktCBL",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "ChTBjFnkmbCHgDRGPz9cD",
        "card_unique_id": "pKdGGghdpnBCzrjwPmkPg",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "RgjMKnDRrfkLK7JRkRjbW",
        "card_unique_id": "QqghkNGDQHkGMRGRt8pDr",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "BpNGQRfJ8nB7tTjq7nmGq",
        "card_unique_id": "bkwMDWGMmKTMd9dKQMt76",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "p8D67M6FPLGtrcmHbfTHJ",
        "card_unique_id": "g9ckPjGmpNNkmbgChTQNR",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "PWffCmzgCpGRcPMzJ9LMD",
        "card_unique_id": "BnQtggKJtBNmpqKR7NWBH",
        "status_active": false,
        "date_announced": "2022-06-24T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-june-2022/"
    },
    {
        "unique_id": "WQ8cRRLg68HRjQpCGzcDP",
        "card_unique_id": "t6MkmHjPRNghmMcMQbqch",
        "status_active": true,
        "date_announced": "2023-01-24T00:00:00.000Z",
        "date_in_effect": "2023-01-30T00:00:00.000Z",
        "planned_end": "until Iyslander becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/banned-and-suspended-announcement/"
    },
    {
        "unique_id": "rpNWJgHdjHFhz9mQgdFHH",
        "card_unique_id": "HFwjczQFRKCgTFHdbjdzW",
        "status_active": true,
        "date_announced": "2023-01-24T00:00:00.000Z",
        "date_in_effect": "2023-01-30T00:00:00.000Z",
        "planned_end": "until Iyslander becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/banned-and-suspended-announcement/"
    },
    {
        "unique_id": "FthHcJzDRbQWgpjPmRWRP",
        "card_unique_id": "nGHhHDgKmGgb7gjwWjHJF",
        "status_active": false,
        "date_announced": "2023-07-03T00:00:00.000Z",
        "date_in_effect": "2023-07-07T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-suspended-announcement-july-3/"
    },
    {
        "unique_id": "TJKwqBmc86HwJnjqbpHH8",
        "card_unique_id": "FLfrm7mBczWhFLBTKmBgJ",
        "status_active": true,
        "date_announced": "2023-09-18T00:00:00.000Z",
        "date_in_effect": "2023-09-22T00:00:00.000Z",
        "planned_end": "until Lexi, Livewire becomes Living Legend",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement-sep19-23/"
    },
    {
        "unique_id": "fdzN8QQLQcDqK6zrwKmTb",
        "card_unique_id": "FLfrm7mBczWhFLBTKmBgJ",
        "status_active": false,
        "date_announced": "2023-11-06T00:00:00.000Z",
        "date_in_effect": "2023-11-06T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-and-suspended-announcement-nov6/"
    },
    {
        "unique_id": "mqWkWW6p6FQzdd9bkQM7D",
        "card_unique_id": "t6MkmHjPRNghmMcMQbqch",
        "status_active": false,
        "date_announced": "2023-11-27T00:00:00.000Z",
        "date_in_effect": "2023-12-01T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/living-legends-iyslander-stormbind-kano-and-kassai-cintari-sellsword/"
    },
    {
        "unique_id": "QmJ76dRd8c8JWMRjbbP9b",
        "card_unique_id": "HFwjczQFRKCgTFHdbjdzW",
        "status_active": false,
        "date_announced": "2023-11-27T00:00:00.000Z",
        "date_in_effect": "2023-12-01T00:00:00.000Z",
        "planned_end": "",
        "legality_article": "https://fabtcg.com/articles/living-legends-iyslander-stormbind-kano-and-kassai-cintari-sellsword/"
    }
]

=== gre99ory/flesh-and-blood-cards/json/english/banned-blitz.json
[
    {
        "unique_id": "kGgpBMLWjk7PqDL9QRmqN",
        "card_unique_id": "9bQFfTFGQWJFWrcJnfQgz",
        "status_active": true,
        "date_announced": "2021-03-18T00:00:00.000Z",
        "date_in_effect": "2021-03-26T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement/"
    },
    {
        "unique_id": "gpFfnRb7phWTjm88NBMtt",
        "card_unique_id": "Nhmj8MBNCmWFC68JkhkNC",
        "status_active": true,
        "date_announced": "2021-03-18T00:00:00.000Z",
        "date_in_effect": "2021-03-26T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement/"
    },
    {
        "unique_id": "TLLHpCcMRrjcNPrqjMLhP",
        "card_unique_id": "hJt6FwT8mhQbcWQLzgHMT",
        "status_active": true,
        "date_announced": "2021-03-18T00:00:00.000Z",
        "date_in_effect": "2021-03-26T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement/"
    },
    {
        "unique_id": "PfrhhnQHPLhn9HgMbr7Ff",
        "card_unique_id": "bkwMDWGMmKTMd9dKQMt76",
        "status_active": true,
        "date_announced": "2021-09-21T00:00:00.000Z",
        "date_in_effect": "2021-09-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-sept21/"
    },
    {
        "unique_id": "RhrwBJrTDL6gjtdRKnctD",
        "card_unique_id": "g9ckPjGmpNNkmbgChTQNR",
        "status_active": true,
        "date_announced": "2021-09-21T00:00:00.000Z",
        "date_in_effect": "2021-09-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-sept21/"
    },
    {
        "unique_id": "jGQkPwLLjpHPJdnPqt9KR",
        "card_unique_id": "BnQtggKJtBNmpqKR7NWBH",
        "status_active": true,
        "date_announced": "2021-09-21T00:00:00.000Z",
        "date_in_effect": "2021-09-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-sept21/"
    },
    {
        "unique_id": "gcjmrhrRcrpGBRg7mwcpt",
        "card_unique_id": "HkDzFgnhCBGn6K9w7RWtC",
        "status_active": true,
        "date_announced": "2022-01-12T00:00:00.000Z",
        "date_in_effect": "2022-01-17T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-errata-bulletin/"
    },
    {
        "unique_id": "gWDzwMKwdwchQfdTdWjPz",
        "card_unique_id": "TJdbQPDBpnLGpNmmN7fhg",
        "status_active": true,
        "date_announced": "2022-01-12T00:00:00.000Z",
        "date_in_effect": "2022-01-17T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-errata-bulletin/"
    },
    {
        "unique_id": "P7h9KBt6hGPQPtwqT9Qpn",
        "card_unique_id": "w77m97tB9GPDzK6ccgkjr",
        "status_active": true,
        "date_announced": "2022-01-12T00:00:00.000Z",
        "date_in_effect": "2022-01-17T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-errata-bulletin/"
    },
    {
        "unique_id": "gGfpFgzz6LHpw6hnc6MkM",
        "card_unique_id": "QnKbrhtk7HFcckCBbFmkt",
        "status_active": true,
        "date_announced": "2022-01-12T00:00:00.000Z",
        "date_in_effect": "2022-01-17T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-and-restricted-announcement-errata-bulletin/"
    },
    {
        "unique_id": "Qn6PbgRPMLpQ7FQncGTQk",
        "card_unique_id": "phCFwdjG8dKDCmr7d7F7M",
        "status_active": true,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "jcCqq7HTQhNWQ8kNdzkmK",
        "card_unique_id": "666mgFjKrrLQhdkpGzNzf",
        "status_active": true,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-05-02T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "6cdMb9ggKt6CTjNHdFjfm",
        "card_unique_id": "wj7qpMrzMjDbn8tmtfPL7",
        "status_active": true,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "gLFwRP7NLJLK7crJQF7zB",
        "card_unique_id": "bkwMDWGMmKTMd9dKQMt76",
        "status_active": false,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "DccLLQrbjMPzQFFRhwzF9",
        "card_unique_id": "g9ckPjGmpNNkmbgChTQNR",
        "status_active": false,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "RPHjFWh86grPW7BjFGhm8",
        "card_unique_id": "BnQtggKJtBNmpqKR7NWBH",
        "status_active": false,
        "date_announced": "2022-04-25T00:00:00.000Z",
        "date_in_effect": "2022-06-24T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announcement/"
    },
    {
        "unique_id": "7hNNHWndKpCfd9Bq8MLLN",
        "card_unique_id": "FfHKcc6HWkdkbC76BwgqQ",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "CPBJdbwKhP9C8QM7DPmKt",
        "card_unique_id": "Tb8rJqp6nH9FhDQgNMgpH",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "cGkkWJDJpHmBppD66dmqp",
        "card_unique_id": "pBLw878jHjmLBLBbtpk6W",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "CTwcjGc8DRRrRtFtbqGHP",
        "card_unique_id": "fMdnz9D9MRDrzMrBFf7Kr",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "z9G6pHjnLqMgcz8RzhqP8",
        "card_unique_id": "nPwjcRFWBmzNQWM6BMcgB",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "bTbdtPgfwKWTThNKFDn98",
        "card_unique_id": "k8wMFCFHtGTtTRfnzKGqQ",
        "status_active": true,
        "date_announced": "2022-08-29T00:00:00.000Z",
        "date_in_effect": "2022-08-30T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/scheduled-banned-suspended-announced/"
    },
    {
        "unique_id": "6CzBnPKTnJKn9jCWp8jgM",
        "card_unique_id": "nGHhHDgKmGgb7gjwWjHJF",
        "status_active": true,
        "date_announced": "2022-10-03T00:00:00.000Z",
        "date_in_effect": "2022-10-07T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-suspended-oct-3/"
    },
    {
        "unique_id": "rpk6GcgdgqnqLpmz9BBzb",
        "card_unique_id": "GBDFTmjdTmgRCdHngGWNR",
        "status_active": true,
        "date_announced": "2022-10-03T00:00:00.000Z",
        "date_in_effect": "2022-10-07T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-suspended-oct-3/"
    },
    {
        "unique_id": "8w7JnN79HGndGfwkgNdwP",
        "card_unique_id": "CrWjLrqtQtppQhQCMt9LH",
        "status_active": true,
        "date_announced": "2022-11-10T00:00:00.000Z",
        "date_in_effect": "2022-11-11T00:00:00.000Z",
        "legality_article": "https://fabtcg.com/articles/banned-suspended-nov-9/"
    }
]
